# Use postgres/example user/password credentials
version: "3.1"
services:
  db:
    container_name: clean_arch_db
    image: postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres"]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: clean
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432
